class ALFAc:
	def a():
		print ('alfa')
	def b():
		print ('bravo')
	def c():
		print ('charlie')
	def d():
		print ('delta')
	def e():
		print ('echo')
	def f():
		print ('foxtrot')
	def g():
		print ('golf')
	def h():
		print ('hotel')
	def i():
		print ('india')
	def j():
		print ('juliett')
	def k():
		print ('kilo')
	def l():
		print ('lima')
	def m():
		print ('mike')
	def n():
		print ('november')
	def o():
		print ('oscar')
	def p():
		print ('papa')
	def q():
		print ('quebec')
	def r():
		print ('romeo')
	def s():
		print ('sierra')
	def t():
		print ('tango')
	def u():
		print ('uniform')
	def v():
		print ('victor')
	def w():
		print ('whiskey')
	def x():
		print ('X-ray')
	def y():
		print ('yankee')
	def z():
		print ('zulu')